"""Sujets Vie B (26-50)."""
TOPICS_B = [
("mon voisin bruyant", "va le voir cool avec une solution, genre horaires calmes, ca passe mieux que de rager seul"),
("apprendre l'anglais", "15 min de serie en VO sous-titres + repeter a voix haute, en 3 mois tu sens la diff"),
("mon stage", "un stage meme nul ca apprend, note tout ce que tu veux PAS refaire, c'est de l'or pour apres"),
("la timidite", "t'es pas le seul, commence par des micro-discussions, boulanger, voisin, ca muscle petit a petit"),
("mon telephone casse", "classique, sauvegarde d'abord, apres on compare reparation vs reconditionne, je t'aide a choisir"),
("le code de la route", "c'est de la logique pas du par coeur, fais des series de 20 et note tes pieges recurrents"),
("ma coloc", "le secret c'est les regles posees tot et cool : menage, bruit, invites, sinon ca pourrit"),
("mon chien", "une balade rituel matin et soir ca change son comportement et ton humeur, gagnant-gagnant"),
("les infos angoissantes", "coupe les notifs, 10 min d'infos par jour ca suffit, protege ta tete"),
("mon premier appart", "check eau chaude, pression, voisins, transport, le reste c'est du decor"),
("le permis", "c'est le stress qui fait rater, respire, l'examinateur veut juste voir que t'es safe"),
("mon copain ma copine", "dis-moi ce qui va et ce qui coince, on demle sans juger, la com ca s'apprend"),
("les soldes", "fais ta liste AVANT, sinon tu achetes du pas-utile, le vrai bon plan c'est ce que tu mets 10 fois"),
("mon sommeil", "heure fixe + lumiere du jour le matin, ton corps adore la routine meme si ta tete rale"),
("les embrouilles en famille", "reste sur les faits pas sur les reproches, Je ressens plutot que Tu es, ca desamorce"),
("mon CV", "une page, resultats chiffres, pas de pavé, tu veux je te relise ligne par ligne"),
("la cantine", "si c'est bof ramene un tupperware 2 fois par semaine, ton ventre et ton wallet te diront merci"),
("mon accent", "ton accent c'est ton histoire, assume, et si tu veux bosser la diction on fait des exos fun"),
("les departs en vacances", "pars tot, playlist prete, snacks, et la route devient un bon souvenir"),
("faire du skate", "protections + 20 min par jour sur du plat, les chutes font partie du jeu au debut"),
("mon ordi qui rame", "nettoie le demarrage et le stockage d'abord, 80 pour cent des lags viennent de la"),
("les profs severes", "ils testent ta constance, rends propre et a l'heure, tu gagnes des points gratuits"),
("mon equipe au foot", "le foot c'est les potes d'abord, le score apres, tu joues quel poste toi"),
("apprendre a nager", "commence en pataugeoire avec un pote, la peur part quand le corps comprend qu'il flotte"),
("mon jardin", "commence par 3 plantes increvables, quand ca pousse ca donne envie de continuer"),
]
