"""Sujets Vie C (51-75)."""
TOPICS_C = [
("mon anniversaire", "fete ce que TOI tu kiffes, petit comite mais bonne bouffe, c'est ca les bons souvenirs"),
("les embouteillages", "podcast ou appel a un pote, transforme le temps perdu en temps cool"),
("mon frigo vide", "pates + oeufs + sauce tomate ca sauve toujours, apres on fait une vraie liste de courses"),
("apprendre la guitare", "10 min d'accords par jour, les doigts font mal 2 semaines puis ca roule"),
("mes cheveux", "teste un petit changement d'abord, et demande au coiffeur ce qui va a TA forme de visage"),
("mon premier job", "arrive 10 min avant, pose des questions, note tout, les debuts c'est fait pour apprendre"),
("les moustiques", "moustiquaire + ventilo ca marche mieux que les produits, crois-moi"),
("mon compte insta", "poste ce que t'aimes vraiment, les stats suivront ou pas mais au moins tu kiffes"),
("la pluie", "bonne veste + playlist et la pluie devient cosy, team automne ou team ete toi"),
("mon grand-pere", "pose-lui des questions sur sa jeunesse, ces histoires valent de l'or et ca lui fait trop plaisir"),
("les courses", "jamais le ventre vide, liste par rayon, tu divises la facture par deux"),
("mon reve bizarre", "raconte-moi, les reves c'est ton cerveau qui range, on decode ensemble"),
("les devoirs", "technique pomodoro 25-5, tel loin, tu finis 2 fois plus vite"),
("mon quartier", "explore a pied un dimanche matin, tu decouvres toujours une rue ou un parc cache"),
("la flemme", "c'est ton corps qui demande une pause ou un sens, 10 min de marche puis on decide"),
("mon pull prefere troue", "un petit point ca se recoud en 5 min, sinon patch cool ca donne du style"),
("les langues regionales", "c'est une richesse, meme 10 mots ca fait plaisir aux anciens"),
("mon prochain voyage", "dis-moi budget et vibe, je te sors un plan qui claque sans te ruiner"),
("les sneakers", "prends ce qui est confortable d'abord, le style suit, tes pieds te diront merci"),
("mon chat qui griffe", "griffoir pres du canape + feliciter quand il l'utilise, ca marche en 2 semaines"),
("les films d'horreur", "si t'aimes flipper mais pas trop je te conseille de commencer soft, tu veux du soft ou du hardcore"),
("mon piano", "gammes 5 min puis un morceau que t'adores, le plaisir d'abord sinon tu laches"),
("la boulangerie", "le pain au levain ca cale mieux et ca se garde, teste la boulangerie artisanale du coin"),
("mon passeport", "check la date 6 mois avant tout voyage, le renouvellement ca prend des semaines"),
("les vide-greniers", "arrive tot, cash, negocie cool, c'est la chasse au tresor du dimanche"),
]
