"""Sujets Vie D (76-100)."""
TOPICS_D = [
("mon equipe de basket", "le basket c'est le collectif et l'energie, tu joues meneur ou interieur"),
("les podcasts", "dis-moi ton mood et je te file 3 podcasts FR qui tuent, trajet = moment prefere"),
("mon velo creve", "kit crevaison + tuto 10 min, la 2e fois tu le fais les yeux fermes"),
("les allergies au pollen", "douche le soir + fenetres fermees le matin, ca change la vie au printemps"),
("mon petit frere", "sois le grand qu'il admire sans le sermonner, joue avec lui 10 min ca vaut tout"),
("les echecs", "apprends un echec et mat en 2 coups puis joue, tu progresses en t'amusant"),
("mon mariage qui approche", "stresse pas sur la perfection, les invites retiennent l'ambiance pas la deco"),
("les serpents j'ai peur", "normal, commence par des videos puis un reptilarium, la peur baisse quand tu comprends"),
("mon potager", "tomates cerises + herbes aromatiques, inratable et tu kiffes cuisiner apres"),
("les concerts", "bouchons d'oreilles + arrive tot pour etre devant, le live ca n'a rien a voir"),
("mon tatouage je hesite", "attends 6 mois avec le dessin sur le frigo, si tu le kiffes toujours fonce"),
("les livres audio", "parfait pour les trajets, commence par un roman que t'as deja aime, tu vas adorer"),
("mon wifi nul", "box en hauteur au centre + redemarrage, sinon repeteur, on diagnostique ensemble"),
("les chamailleries au taf", "reste pro sur ecrit, regle en face cool, jamais de clash par mail"),
("mon pull qui gratte", "lave-le a froid avec vinaigre blanc, si ca gratte toujours offre-le, la vie est trop courte"),
("les marches en foret", "foret + silence ca recharge mieux que 2h de tel, teste dimanche matin tot"),
("mon fils qui veut un tel", "fixe les regles avant : horaires, applis, et montre l'exemple, dur mais efficace"),
("les series coreennes", "commence par une courte, c'est addictif, tu veux romance ou thriller"),
("mon scooter", "entretien + casque attache, et roule cool sous la pluie, je te file la check-list"),
("cuisiner des pates parfaites", "eau tres salee bouillante, al dente, une louche d'eau dans la sauce, resto a la maison"),
("mon dentiste j'ai peur", "dis-le direct au dentiste, ils ont des protocoles doux maintenant, et musique pendant"),
("les oiseaux du jardin", "mangeoire + eau, en 2 semaines t'as un spectacle gratuit chaque matin"),
("mon premier entretien", "prepare 3 histoires de reussites, arrive tot, souris, les recruteurs veulent du potentiel"),
("la guitare qui sonne faux", "accordeur gratuit + changer les cordes tous les 3 mois, ca sonne neuf direct"),
("mon voisin sympa", "un petit gateau ou un bonjour regulier ca cree une ambiance de fou dans l'immeuble"),
]
